### ISSUE TITLE
Duplicate character card.

### ISSUE THREAD

**Issue by nsrivastava999** [RishabhKodes/heisenberg-s_world#1]
Stacey Ehrmantraut's character card is present more than once. Please fix it.

**Comment by RishabhKodes** [comment]
> Stacey Ehrmantraut's character card is present more than once. Please fix it.

Thanks for pointing that out,
But that's an issue with the Breaking Bad API, that I am using, [this](https://breakingbadapi.com/documentation). I can't fix it from my side.
